### ISSUE TITLE
Plugin name conflicts with other projects

### ISSUE THREAD

**Issue by kooskaspers** [KZDKM/Hyprspace#2]
Great initiative! Definitely going to try out your plugin. 
Be aware there's already a Hyprland plugin with the same name (WIP): https://github.com/Lindenk/hyprspace

**Comment by KZDKM** [comment]
Thanks for the reminder! I guess the name Hypr+space comes pretty naturally for anyone trying to make a workspace manager for hyprland and I've already found numerous other plugin projects named hyprspace. I have never thought of this since I didnt consider publishing it, i will try to sort out the naming conflict.

**Comment by KZDKM** [comment]
Other projects seems to be inactive, wouldn't be a problem for now as long as there are no conflicts in hyprpm or nix naming.

**Comment by dmadisetti** [comment]
@KZDKM just a note that the nix is case sensitive as **H**yprspace. When I initially tried to package, there was a namespace collision with *h*yprspace
