### ISSUE TITLE
Hyprspace layer is part of preview in overview

### ISSUE THREAD

**Issue by KAGEYAM4** [KZDKM/Hyprspace#94]
2nd from right -->

![image](https://github.com/user-attachments/assets/34c3f57d-a617-4e68-9254-0f2be87c6f4e)

**Comment by myamusashi** [comment]
Expected, can't remove that part

**Comment by KAGEYAM4** [comment]
@myamusashi  okay, so i rechecked the demo video and it seems that current active workspace is not shown in hyprspace. which config is responsible for this ?

**Comment by myamusashi** [comment]
drawActiveWorkspace   = 0

**Comment by myamusashi** [comment]
yep

**Comment by KAGEYAM4** [comment]
The demo video, the workspace was starting one, thats why i got confused. I will just create feature request regarding these.

**Comment by KAGEYAM4** [comment]
Can it not be fixed ? Is this plugin limitation ?

**Comment by myamusashi** [comment]
I'm also confused. What do you expect here? You want the workspace to be at the beginning instead of in the middle?

**Comment by KZDKM** [comment]
Uhh since the overview changes the layout of the active workspace, I figured displaying the panel inside the overview would be better. Without rendering a dummy panel there would be an awkward blank in the active workspace view. If you dont want the layout of the active workspace to change, you could make the windows not dodge the panel by setting `affectStrut` to false.
